// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250601215016_modelupdate44")]
    partial class modelupdate44
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Analytics.DashboardMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveCampaigns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_campaigns");

                    b.Property<decimal>("AverageLifetimeValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("average_lifetime_value");

                    b.Property<decimal>("CampaignSuccessRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("campaign_success_rate");

                    b.Property<decimal>("ChurnRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("churn_rate");

                    b.Property<Guid>("CompanyId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("HighRiskCustomers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("high_risk_customers");

                    b.Property<DateTime>("MetricDate")
                        .HasColumnType("date")
                        .HasColumnName("metric_date");

                    b.Property<decimal>("RevenueRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("revenue_recovered");

                    b.Property<int>("TotalCustomers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_customers");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_metrics");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_dashboard_metrics_company_id");

                    b.HasIndex("MetricDate")
                        .HasDatabaseName("ix_dashboard_metrics_metric_date");

                    b.HasIndex("CompanyId", "MetricDate")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_metrics_company_date");

                    b.ToTable("dashboard_metrics", "public");
                });

            modelBuilder.Entity("Domain.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClickedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("clicked_count");

                    b.Property<Guid>("CompanyId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("ConvertedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("converted_count");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OpenedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("opened_count");

                    b.Property<decimal>("RevenueRecovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("revenue_recovered");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("scheduled_date");

                    b.Property<Guid?>("SegmentId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<int>("SentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sent_count");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("sent_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_campaigns_company_id");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("ix_campaigns_scheduled_date");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_campaigns_segment_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_campaigns_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_campaigns_type");

                    b.ToTable("campaigns", "public");
                });

            modelBuilder.Entity("Domain.Campaigns.CampaignStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<int>("ClickedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("clicked_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("ConvertedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("converted_count");

                    b.Property<TimeSpan>("Delay")
                        .HasColumnType("interval")
                        .HasColumnName("delay");

                    b.Property<int>("OpenedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("opened_count");

                    b.Property<int>("SentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sent_count");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_campaign_steps");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_campaign_steps_campaign_id");

                    b.HasIndex("CampaignId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_steps_campaign_order");

                    b.ToTable("campaign_steps", "public");
                });

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime?>("ChurnPredictionDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("churn_prediction_date");

                    b.Property<string>("ChurnRiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Low")
                        .HasColumnName("churn_risk_level");

                    b.Property<decimal>("ChurnRiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("churn_risk_score");

                    b.Property<Guid>("CompanyId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<decimal>("FeatureUsagePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("feature_usage_percentage");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_login_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("last_payment_date");

                    b.Property<DateTime?>("LastPaymentFailureDate")
                        .HasColumnType("date")
                        .HasColumnName("last_payment_failure_date");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("LifetimeValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("lifetime_value");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<decimal>("MonthlyRecurringRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthly_recurring_revenue");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("date")
                        .HasColumnName("next_billing_date");

                    b.Property<int>("PaymentFailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("payment_failure_count");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("date")
                        .HasColumnName("subscription_end_date");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("date")
                        .HasColumnName("subscription_start_date");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subscription_status");

                    b.Property<int>("SupportTicketCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("support_ticket_count");

                    b.Property<string>("SyncVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sync_version");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("time_zone");

                    b.Property<int>("WeeklyLoginFrequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weekly_login_frequency");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("ChurnRiskScore")
                        .HasDatabaseName("ix_customers_churn_risk_score");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customers_company_id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_customers_email");

                    b.HasIndex("LastLoginDate")
                        .HasDatabaseName("ix_customers_last_login");

                    b.HasIndex("PaymentStatus")
                        .HasDatabaseName("ix_customers_payment_status");

                    b.HasIndex("SubscriptionStatus")
                        .HasDatabaseName("ix_customers_subscription_status");

                    b.HasIndex("CompanyId", "ExternalId", "Source")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_company_external_source");

                    b.ToTable("customers", "public");
                });

            modelBuilder.Entity("Domain.Customers.CustomerActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_customer_activities");

                    b.HasIndex("ActivityDate")
                        .HasDatabaseName("ix_customer_activities_activity_date");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_activities_customer_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_customer_activities_type");

                    b.HasIndex("CustomerId", "ActivityDate")
                        .HasDatabaseName("ix_customer_activities_customer_date");

                    b.ToTable("customer_activities", "public");
                });

            modelBuilder.Entity("Domain.Customers.CustomerSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageChurnRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("average_churn_rate");

                    b.Property<decimal>("AverageLifetimeValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("average_lifetime_value");

                    b.Property<decimal>("AverageRevenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("average_revenue");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasDefaultValue("#3b82f6")
                        .HasColumnName("color");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("integer")
                        .HasColumnName("customer_count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_customer_segments");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_customer_segments_company_id");

                    b.ToTable("customer_segments", "public");
                });

            modelBuilder.Entity("Domain.Imports.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("FailedRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_records");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<string>("ImportSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("import_source");

                    b.Property<string>("ImportSummary")
                        .HasColumnType("text")
                        .HasColumnName("import_summary");

                    b.Property<int>("ProcessedRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processed_records");

                    b.Property<int>("SkippedRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("skipped_records");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("successful_records");

                    b.Property<int>("TotalRecords")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_records");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text")
                        .HasColumnName("validation_errors");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_import_jobs_company_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_import_jobs_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_jobs_status");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_import_jobs_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_import_jobs_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_import_jobs_status_created");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_import_jobs_user_status");

                    b.ToTable("import_jobs", "public");
                });

            modelBuilder.Entity("Domain.Integration.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Configuration")
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<Dictionary<string, string>>("Credentials")
                        .HasColumnType("jsonb")
                        .HasColumnName("credentials");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SyncedRecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("synced_record_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_integrations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_integrations_user_id");

                    b.ToTable("integrations", "public");
                });

            modelBuilder.Entity("Domain.Notification.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_text");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("action_url");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_notifications_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_notifications_expires_at");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("ix_notifications_is_read");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_created");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_read");

                    b.ToTable("notifications", "public");
                });

            modelBuilder.Entity("Domain.Segments.ChurnPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<DateTime>("PredictionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prediction_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Dictionary<string, decimal>>("RiskFactors")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_factors");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<decimal>("RiskScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("risk_score");

                    b.HasKey("Id")
                        .HasName("pk_churn_predictions");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_churn_predictions_customer_id");

                    b.HasIndex("PredictionDate")
                        .HasDatabaseName("ix_churn_predictions_prediction_date");

                    b.HasIndex("CustomerId", "PredictionDate")
                        .HasDatabaseName("ix_churn_predictions_customer_date");

                    b.ToTable("churn_predictions", "public");
                });

            modelBuilder.Entity("Domain.Segments.SegmentCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operator");

                    b.Property<Guid>("SegmentId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_segment_criteria");

                    b.HasIndex("Field")
                        .HasDatabaseName("ix_segment_criteria_field");

                    b.HasIndex("SegmentId")
                        .HasDatabaseName("ix_segment_criteria_segment_id");

                    b.ToTable("segment_criteria", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Users.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("domain");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_domain");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_companies_name");

                    b.ToTable("companies", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_users_company_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("campaign_customers", b =>
                {
                    b.Property<Guid>("campaign_id")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("customer_id")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.HasKey("campaign_id", "customer_id")
                        .HasName("pk_campaign_customers");

                    b.HasIndex("campaign_id")
                        .HasDatabaseName("ix_campaign_customers_campaign_id");

                    b.HasIndex("customer_id")
                        .HasDatabaseName("ix_campaign_customers_customer_id");

                    b.ToTable("campaign_customers", "public");
                });

            modelBuilder.Entity("Domain.Analytics.DashboardMetrics", b =>
                {
                    b.HasOne("Domain.Users.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dashboard_metrics_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Campaigns.Campaign", b =>
                {
                    b.HasOne("Domain.Users.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_companies_company_id");

                    b.HasOne("Domain.Customers.CustomerSegment", "Segment")
                        .WithMany("Campaigns")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_campaigns_customer_segments_segment_id");

                    b.Navigation("Company");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Domain.Campaigns.CampaignStep", b =>
                {
                    b.HasOne("Domain.Campaigns.Campaign", "Campaign")
                        .WithMany("Steps")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_steps_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.HasOne("Domain.Users.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Customers.CustomerActivity", b =>
                {
                    b.HasOne("Domain.Customers.Customer", "Customer")
                        .WithMany("Activities")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_activities_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Customers.CustomerSegment", b =>
                {
                    b.HasOne("Domain.Users.Company", "Company")
                        .WithMany("Segments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_segments_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Imports.ImportJob", b =>
                {
                    b.HasOne("Domain.Users.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_jobs_companies_company_id");

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_jobs_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Integration.Integration", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("Integrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Notification.Notification", b =>
                {
                    b.HasOne("Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Segments.ChurnPrediction", b =>
                {
                    b.HasOne("Domain.Customers.Customer", "Customer")
                        .WithMany("ChurnPredictions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_churn_predictions_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Segments.SegmentCriteria", b =>
                {
                    b.HasOne("Domain.Customers.CustomerSegment", "Segment")
                        .WithMany("Criteria")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segment_criteria_customer_segments_segment_id");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.HasOne("Domain.Users.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_users_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("campaign_customers", b =>
                {
                    b.HasOne("Domain.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_customers_campaigns_campaign_id");

                    b.HasOne("Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_customers_customers_customer_id");
                });

            modelBuilder.Entity("Domain.Campaigns.Campaign", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Domain.Customers.Customer", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ChurnPredictions");
                });

            modelBuilder.Entity("Domain.Customers.CustomerSegment", b =>
                {
                    b.Navigation("Campaigns");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("Domain.Users.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Segments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("Integrations");
                });
#pragma warning restore 612, 618
        }
    }
}
